project:
  type: website
  output-dir: docs

website:
  title: "Viraj R. Chordiya"
  open-graph: true
  navbar:
    background: primary
    search: true
    right:
      #- posts.qmd
      - text: Projects
        href: projects.qmd
      - text: "Resume"
        file: Viraj_Chordiya_Resume.pdf
      - icon: github
        href: https://github.com/viraj-550
      - icon: linkedin
        href: https://www.linkedin.com/in/virajchordiya/
format:
  html:
    theme: minty
    css: styles.css

editor: visual
