project:
  type: website
  output-dir: docs

website:
  title: "Viraj R. Chordiya"
  open-graph: true
  navbar:
    background: primary
    search: true
    left:
      - text: Research
        href: research.qmd
      # - text: Projects
      #   href: projects.qmd
      # - text: Posts
      #   href: posts.qmd
      - text: "Resume"
        file: cv_viraj_chordiya.pdf
      - icon: github
        href: https://github.com/viraj-550
  page-navigation: true
  back-to-top-navigation: true
  # announcement:   # Announcements
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Alert** - this is some information that you should pay attention to"
  #   position: below-navbar

format:
  html:
    theme: 
      - yeti # from minty
      - custom_theme.scss
    css: 
      - styles.css
      - academicons-1.9.4/css/academicons.min.css
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 200px
      gutter-width: 1.5rem
